### ISSUE TITLE
Is there a way to prevent it from aborting on compiling error?

### ISSUE THREAD

**Issue by ghaschel** [js-seth-h/grunt-service#3]
I love this, but the fact that it abort on any compiling error makes me mad. Is there a way to disable it, and make it just keep running, and waiting for the correct code? 
Sometimes when i miss something, and press ctrl+s, it abort itself because of a missing semicolon, or anything like that... That is not pratical at all...

Thanks a lot. <3

**Comment by ghaschel** [comment]
I love your cat btw.

**Comment by js-seth-h** [comment]
sorry for late. 
I also use this for running development sever that auto reaload when code change. 
but, in my case, grunt process is not abort even syntax error. 
I am not sure that feature come from this mudule or not. 
anyway. I share my grunt config, I hope that it is helpful to solve issue.

```javascript
  grunt.initConfig    
 
    fastWatch:
      cwd:     
        dir : '.' 
        ignoreSubDir : ignoreDir 
        trigger:
          server:  
            care : serverCares
            tasks: ["service:server:restart"] 
          build:
            care : buildCares
            tasks: ['build']

    concurrent:
      server:
        tasks: ["fastWatch:cwd", 'service:server', 'build']
        options:  
          logConcurrentOutput: true  

    service:  
      server: 
        shellCommand : "coffee Server.coffee"  
        pidFile : pidpath
        options : 
          stdio : 'inherit' 
      build: 
        shellCommand : "coffee Build.coffee"
        option:
          failOnError: false
      mongo:
        shellCommand: "cd D:/#MongoDB/mongodb &&  ./bin/mongod.exe  --config ../mongo.conf.yaml"
        # blocking: true


  grunt.loadNpmTasks 'grunt-concurrent'
  grunt.loadNpmTasks 'grunt-service'
  grunt.loadNpmTasks 'grunt-fast-watch'
```
